---

name: CI

"on":
  pull_request:
  push:
  schedule:
    - cron: '29 4 1 * *'

jobs:
  build:
    strategy:
      matrix:
        go:
          - 1.11.x  # debian buster
          - 1.13.x  # ubuntu focal
          - 1.15.x  # debian bullseye
          - 1.x     # latest

    name: Go ${{ matrix.go }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up GITHUB_ENV
        run: |
          go version | sed 's/^go version /GOVERSION=/' | \
          tr ' /' '-' >>$GITHUB_ENV
          go env GOPATH | sed 's/^/GOPATH=/' >>$GITHUB_ENV
          go env GOCACHE | sed 's/^/GOCACHE=/' >>$GITHUB_ENV

      - name: Set up Go cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ env.GOVERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ env.GOVERSION }}-

      - name: Set up build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -q \
          appstream-util \
          gettext \
          libgtk-3-dev \
          libxml2-utils \
          shellcheck \
          yamllint

      - run: make
      - run: make check
      - run: make test

  flatpak-builder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
        repo:
          - appcenter
          - flathub
        include:
          - repo: appcenter
            reporef: https://flatpak.elementary.io/repo.flatpakrepo
          - repo: flathub
            reporef: https://flathub.org/repo/flathub.flatpakrepo

    steps:
      - uses: actions/checkout@v2

      - name: Set up flatpak-builder
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q flatpak flatpak-builder

      - name: Set up flatpak-builder cache
        uses: actions/cache@v2
        with:
          path: .flatpak-builder
          key: >
            ${{ matrix.repo }}-${{ matrix.arch }}-${{ hashFiles('**/go.sum')
            }}-${{ hashFiles('flatpak/flathub.yml.in') }}
          restore-keys: ${{ matrix.repo }}-${{ matrix.arch }}-

      - name: Configure ${{ matrix.repo }}
        run: >
          flatpak --user remote-add --if-not-exists --from
          ${{ matrix.repo }} ${{ matrix.reporef }}

      - run: make ${{ matrix.repo }}
