---

name: CI

"on":
  pull_request:
  push:
  schedule:
    - cron: '29 4 1 * *'

jobs:
  build-and-test:
    strategy:
      matrix:
        go:
          - 1.11.x  # debian buster
          - 1.13.x  # ubuntu focal
          - 1.15.x  # debian bullseye
          - 1.x     # latest

    name: build and test (go ${{ matrix.go }})

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up GITHUB_ENV
        run: |
          go version | sed 's/^go version /GOVERSION=/' | \
          tr ' /' '-' >>$GITHUB_ENV
          go env GOPATH | sed 's/^/GOPATH=/' >>$GITHUB_ENV
          go env GOCACHE | sed 's/^/GOCACHE=/' >>$GITHUB_ENV

      - name: Set up Go cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ env.GOVERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ env.GOVERSION }}-

      - name: Set up build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -q \
          appstream-util \
          gettext \
          libgtk-3-dev \
          libxml2-utils \
          shellcheck \
          yamllint

      - run: make
      - run: make check
      - run: make test

  flatpak-builder:
    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
        repo:
          - appcenter
          - flathub
        include:
          - repo: appcenter
            repo-url: https://flatpak.elementary.io/repo.flatpakrepo
          - repo: flathub
            repo-url: https://flathub.org/repo/flathub.flatpakrepo

    name: flatpak-builder (${{ matrix.repo }}, ${{ matrix.arch }})

    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dnf -y install docker

      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - run: make flatpak/${{ matrix.repo }}.yml

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          arch: ${{ matrix.arch }}
          manifest-path: flatpak/${{ matrix.repo }}.yml
          repository-name: ${{ matrix.repo }}
          repository-url: ${{ matrix.repo-url }}
