---

name: CI

"on":
  pull_request:
  push:
  schedule:
    - cron: '29 4 1 * *'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.17.x
          - 1.18.x  # ubuntu jammy
          - 1.19.x
          - 1.20.x
          - 1.x     # latest

    name: go${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Set up build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -q \
          appstream-util \
          gettext \
          libgtk-3-dev \
          libxml2-utils \
          shellcheck \
          yamllint

      - run: go mod graph
      - run: make check
      - run: make
      - run: make test

  flatpak-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          # TODO: Use go.mod once go.mod go version >= 1.18 for the -o flag.
          # go-version-file: go.mod
          go-version: 1.18.x

      - run: go mod graph
      - run: make flatpak/modules.txt
      - run: make flatpak/appcenter.yml
      - run: make flatpak/flathub.yml

      - uses: actions/upload-artifact@v3
        with:
          name: flatpak-config
          if-no-files-found: error
          path: |
            flatpak/modules.txt
            flatpak/*.yml

  flatpak-builder:
    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
        repo:
          - appcenter
          - flathub
        include:
          - repo: appcenter
            repo-url: https://flatpak.elementary.io/repo.flatpakrepo
            image: bilelmoussaoui/flatpak-github-actions:elementary-juno
          - repo: flathub
            repo-url: https://flathub.org/repo/flathub.flatpakrepo
            image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08

    name: ${{ matrix.repo }}-${{ matrix.arch }}
    needs: flatpak-config
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.image }}
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: flatpak-config
          path: flatpak

      - name: Install QEMU dependencies
        if: ${{ matrix.arch != 'x86_64' }}
        run: dnf -y install docker

      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@master
        with:
          manifest-path: flatpak/${{ matrix.repo }}.yml
          repository-name: ${{ matrix.repo }}
          repository-url: ${{ matrix.repo-url }}
          arch: ${{ matrix.arch }}
          cache: false
          build-bundle: false
