---

name: CI

"on":
  pull_request:
  push:
  schedule:
    - cron: '29 4 1 * *'

jobs:
  build-and-test:
    strategy:
      matrix:
        go:
          - 1.13.x  # ubuntu focal
          - 1.15.x  # debian bullseye
          - 1.16.x  # debian bookworm
          - 1.18.x  # ubuntu jammy
          - 1.x     # latest

    name: go${{ matrix.go }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Set up GITHUB_ENV
        run: |
          go version | sed 's/^go version /GOVERSION=/' | \
          tr ' /' '-' >>$GITHUB_ENV
          go env GOPATH | sed 's/^/GOPATH=/' >>$GITHUB_ENV
          go env GOCACHE | sed 's/^/GOCACHE=/' >>$GITHUB_ENV

      - name: Set up Go cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ env.GOVERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ env.GOVERSION }}-

      - name: Set up build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -q \
          appstream-util \
          gettext \
          libgtk-3-bin \
          libgtk-3-dev \
          libxml2-utils \
          shellcheck \
          yamllint

      - run: make check
      - run: go mod graph
      - run: make
      - run: make test

  flatpak-builder:
    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
        repo:
          - appcenter
          - flathub
        include:
          - repo: appcenter
            repo-url: https://flatpak.elementary.io/repo.flatpakrepo
            image: bilelmoussaoui/flatpak-github-actions:elementary-juno
          - repo: flathub
            repo-url: https://flathub.org/repo/flathub.flatpakrepo
            image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08

    name: ${{ matrix.repo }}-${{ matrix.arch }}

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.image }}
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf -y install docker go make

      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - run: make flatpak/${{ matrix.repo }}.yml
      - run: go mod graph
      - run: cat flatpak/${{ matrix.repo }}.yml

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: com.github.rkoesters.xkcd-gtk.${{ matrix.repo }}.flatpak
          manifest-path: flatpak/${{ matrix.repo }}.yml
          repository-name: ${{ matrix.repo }}
          repository-url: ${{ matrix.repo-url }}
          cache-key: ${{ matrix.repo }}-${{ hashFiles('flatpak/*.yml') }}
          arch: ${{ matrix.arch }}
